#!/usr/bin/env python3
"""Single-entry lightweight downloader-to-EPUB pipeline product."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def default_config() -> dict[str, Any]:
    return {
        "job_name": "example-job",
        "job_root": "",
        "comic_path_word": "yanyanzhixiaofangdui",
        "group_path_word": "default",
        "chapter_limit": 3,
        "author": "Unknown",
        "title": "Merged anthology",
        "kcc_cmd": "/tmp/kcc-venv/bin/kcc-c2e",
        "profile": "KS",
        "language": "zh",
        "description": "Generated by manga-pipeline-lite",
        "contributor": "manga-pipeline-lite",
        "image_workers": 8,
        "skip_existing": True,
        "max_images_per_chapter": None,
        "steps": {
            "download": True,
            "package": True,
            "merge": True,
        },
    }


def resolve_command_value(root: Path, value: str) -> str:
    candidate = Path(value).expanduser()
    if candidate.is_absolute():
        return str(candidate)
    if value.startswith(".") or "/" in value or "\\" in value:
        return str((root / candidate).resolve())
    return value


def load_config(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise SystemExit("Config must be a JSON object")
    merged = default_config()
    incoming_steps = data.get("steps")
    if isinstance(incoming_steps, dict):
        merged["steps"].update(incoming_steps)
        data = dict(data)
        data.pop("steps", None)
    merged.update(data)
    required = ["job_name", "comic_path_word", "group_path_word", "chapter_limit", "author", "title", "kcc_cmd"]
    for key in required:
        value = merged.get(key)
        if value in (None, ""):
            raise SystemExit(f"Missing config field: {key}")
    return merged


def run_command(
    command: list[str],
    *,
    capture_output: bool = False,
    announce: bool = True,
) -> subprocess.CompletedProcess[str]:
    if announce:
        print("RUN:", " ".join(command))
    return subprocess.run(
        command,
        check=True,
        text=True,
        capture_output=capture_output,
    )


def component_paths(root: Path) -> dict[str, Path]:
    return {
        "downloader": root / "apps" / "copymanga-headless-lite" / "copymanga_downloader.py",
        "packager": root / "apps" / "manga-pipeline-lite" / "postprocess" / "manga_packager.py",
        "plan_builder": root / "apps" / "manga-pipeline-lite" / "postprocess" / "make_merge_plan.py",
        "merger": root / "apps" / "manga-pipeline-lite" / "postprocess" / "merge_epub_by_order.py",
    }


def resolve_names(root: Path, comic_path_word: str, group_path_word: str) -> tuple[str, str]:
    downloader = component_paths(root)["downloader"]
    result = run_command(
        [
            sys.executable,
            str(downloader),
            "comic",
            comic_path_word,
            "--json",
        ],
        capture_output=True,
        announce=False,
    )
    payload = json.loads(result.stdout)
    comic_name = str(payload["name"])
    groups = {item["path_word"]: item["name"] for item in payload["groups"]}
    if group_path_word not in groups:
        raise SystemExit(f"Group not found in comic metadata: {group_path_word}")
    return comic_name, str(groups[group_path_word])


def paths_for_job(root: Path, config: dict[str, Any]) -> dict[str, Path]:
    configured_root = str(config.get("job_root") or "").strip()
    if configured_root:
        job_root = Path(configured_root).expanduser().resolve()
    else:
        job_root = root / "runs" / str(config["job_name"])
    return {
        "job_root": job_root,
        "downloads": job_root / "downloads",
        "epubs": job_root / "epubs",
        "merged": job_root / "merged",
        "config_lock": job_root / "config.lock.json",
        "result": job_root / "result.json",
        "plan": job_root / "epubs" / "merge-plan.json",
    }


def ensure_job_dirs(job_paths: dict[str, Path]) -> None:
    for key in ("job_root", "downloads", "epubs", "merged"):
        job_paths[key].mkdir(parents=True, exist_ok=True)


def kcc_available(command: str) -> bool:
    candidate = Path(command)
    if candidate.is_file():
        return True
    return shutil.which(command) is not None


def bool_steps(config: dict[str, Any]) -> dict[str, bool]:
    raw = config.get("steps") or {}
    if not isinstance(raw, dict):
        raise SystemExit("Config field 'steps' must be an object")
    return {
        "download": bool(raw.get("download", True)),
        "package": bool(raw.get("package", True)),
        "merge": bool(raw.get("merge", True)),
    }


def write_result(job_paths: dict[str, Path], payload: dict[str, Any]) -> None:
    job_paths["result"].write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def stage_metadata(root: Path, config: dict[str, Any]) -> dict[str, Any]:
    comic_name, group_name = resolve_names(root, str(config["comic_path_word"]), str(config["group_path_word"]))
    return {
        "comic_name": comic_name,
        "group_name": group_name,
        "input_root_name": str(Path(comic_name) / group_name),
    }


def stage_download(
    *,
    root: Path,
    config: dict[str, Any],
    product_paths: dict[str, Path],
    job_paths: dict[str, Path],
) -> dict[str, Any]:
    command = [
        sys.executable,
        str(product_paths["downloader"]),
        "download-group",
        str(config["comic_path_word"]),
        "--group",
        str(config["group_path_word"]),
        "--limit",
        str(config["chapter_limit"]),
        "--output-root",
        str(job_paths["downloads"]),
        "--image-workers",
        str(config["image_workers"]),
    ]
    max_images = config.get("max_images_per_chapter")
    if max_images not in (None, ""):
        command.extend(["--max-images", str(max_images)])
    if bool(config.get("skip_existing")):
        command.append("--skip-existing")
    run_command(command)
    return stage_metadata(root, config)


def stage_package(
    *,
    root: Path,
    config: dict[str, Any],
    product_paths: dict[str, Path],
    job_paths: dict[str, Path],
    metadata: dict[str, Any],
) -> dict[str, Any]:
    input_root = job_paths["downloads"] / str(metadata["comic_name"]) / str(metadata["group_name"])
    command = [
        sys.executable,
        str(product_paths["packager"]),
        "--input-root",
        str(input_root),
        "--output-root",
        str(job_paths["epubs"]),
        "--kcc-cmd",
        resolve_command_value(root, str(config["kcc_cmd"])),
        "--profile",
        str(config["profile"]),
    ]
    if bool(config.get("skip_existing")):
        command.append("--skip-existing")
    run_command(command)
    return {
        "input_root": str(input_root),
        "epubs_root": str(job_paths["epubs"]),
    }


def stage_merge(
    *,
    config: dict[str, Any],
    product_paths: dict[str, Path],
    job_paths: dict[str, Path],
) -> dict[str, Any]:
    merged_epub = job_paths["merged"] / f"{str(config['title']).replace(' ', '_')}.epub"
    run_command(
        [
            sys.executable,
            str(product_paths["plan_builder"]),
            "--epub-dir",
            str(job_paths["epubs"]),
            "--output",
            str(merged_epub),
            "--title",
            str(config["title"]),
            "--author",
            str(config["author"]),
            "--language",
            str(config["language"]),
            "--description",
            str(config["description"]),
            "--contributor",
            str(config["contributor"]),
            "--plan",
            str(job_paths["plan"]),
        ]
    )
    run_command(
        [
            sys.executable,
            str(product_paths["merger"]),
            "--plan",
            str(job_paths["plan"]),
        ]
    )
    return {
        "merge_plan": str(job_paths["plan"]),
        "merged_epub": str(merged_epub),
    }


def build_result(
    *,
    config: dict[str, Any],
    job_paths: dict[str, Path],
    metadata: dict[str, Any],
    executed_steps: list[str],
    outputs: dict[str, Any],
) -> dict[str, Any]:
    return {
        "job_name": config["job_name"],
        "job_root": str(job_paths["job_root"]),
        "comic_path_word": config["comic_path_word"],
        "comic_name": metadata["comic_name"],
        "group_path_word": config["group_path_word"],
        "group_name": metadata["group_name"],
        "chapter_limit": config["chapter_limit"],
        "executed_steps": executed_steps,
        "downloads_root": str(job_paths["downloads"]),
        **outputs,
    }


def command_init_config(args: argparse.Namespace) -> int:
    output = Path(args.output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(default_config(), ensure_ascii=False, indent=2), encoding="utf-8")
    print(output)
    return 0


def command_doctor(args: argparse.Namespace) -> int:
    root = repo_root()
    config_path = Path(args.config).resolve()
    config = load_config(config_path)
    product_paths = component_paths(root)
    report = {
        "config_path": str(config_path),
        "python": sys.executable,
        "job_root": str(paths_for_job(root, config)["job_root"]),
        "steps": bool_steps(config),
        "components": {name: str(path) for name, path in product_paths.items()},
        "missing_components": [name for name, path in product_paths.items() if not path.is_file()],
        "kcc_cmd": str(config["kcc_cmd"]),
        "resolved_kcc_cmd": resolve_command_value(root, str(config["kcc_cmd"])),
        "kcc_available": kcc_available(resolve_command_value(root, str(config["kcc_cmd"]))),
    }
    if args.check_network:
        report["metadata"] = stage_metadata(root, config)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


def run_selected_steps(args: argparse.Namespace, selected_steps: list[str]) -> int:
    root = repo_root()
    config_path = Path(args.config).resolve()
    config = load_config(config_path)
    product_paths = component_paths(root)
    job_paths = paths_for_job(root, config)
    ensure_job_dirs(job_paths)
    job_paths["config_lock"].write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")

    metadata = stage_metadata(root, config)
    outputs: dict[str, Any] = {}
    for step in selected_steps:
        if step == "download":
            stage_download(root=root, config=config, product_paths=product_paths, job_paths=job_paths)
        elif step == "package":
            outputs.update(
                stage_package(
                    root=root,
                    config=config,
                    product_paths=product_paths,
                    job_paths=job_paths,
                    metadata=metadata,
                )
            )
        elif step == "merge":
            outputs.update(stage_merge(config=config, product_paths=product_paths, job_paths=job_paths))

    result = build_result(
        config=config,
        job_paths=job_paths,
        metadata=metadata,
        executed_steps=selected_steps,
        outputs=outputs,
    )
    write_result(job_paths, result)
    print(job_paths["result"])
    return 0


def command_download(args: argparse.Namespace) -> int:
    return run_selected_steps(args, ["download"])


def command_package(args: argparse.Namespace) -> int:
    return run_selected_steps(args, ["package"])


def command_merge(args: argparse.Namespace) -> int:
    return run_selected_steps(args, ["merge"])


def command_run(args: argparse.Namespace) -> int:
    config = load_config(Path(args.config).resolve())
    configured_steps = bool_steps(config)
    selected_steps = [name for name in ("download", "package", "merge") if configured_steps[name]]
    if not selected_steps:
        raise SystemExit("No steps are enabled in config.steps")
    return run_selected_steps(args, selected_steps)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Lightweight product entrypoint for downloader -> EPUB -> merge")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init-config", help="Write a starter config JSON")
    init_parser.add_argument("--output", required=True)
    init_parser.set_defaults(func=command_init_config)

    doctor_parser = subparsers.add_parser("doctor", help="Check product dependencies and component paths")
    doctor_parser.add_argument("--config", required=True)
    doctor_parser.add_argument("--check-network", action="store_true", help="Also resolve comic/group metadata via network")
    doctor_parser.set_defaults(func=command_doctor)

    download_parser = subparsers.add_parser("download", help="Run only the downloader stage")
    download_parser.add_argument("--config", required=True)
    download_parser.set_defaults(func=command_download)

    package_parser = subparsers.add_parser("package", help="Run only the packaging stage")
    package_parser.add_argument("--config", required=True)
    package_parser.set_defaults(func=command_package)

    merge_parser = subparsers.add_parser("merge", help="Run only the merge stage")
    merge_parser.add_argument("--config", required=True)
    merge_parser.set_defaults(func=command_merge)

    run_parser = subparsers.add_parser("run", help="Run the full downloader-to-EPUB pipeline")
    run_parser.add_argument("--config", required=True)
    run_parser.set_defaults(func=command_run)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
