#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 5 ]]; then
  cat <<'EOF'
Usage:
  run_wsl_copymanga_to_epub.sh <comic_path_word> <group_path_word> <chapter_limit> <author> <output_dir> [title]

Example:
  run_wsl_copymanga_to_epub.sh yanyanzhixiaofangdui default 3 "大久保笃" /mnt/d/GPT_Project/Piclaw/runs/fire-force-e2e "炎炎之消防隊 1-3卷 合集"
EOF
  exit 64
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMIC_PATH_WORD="$1"
GROUP_PATH_WORD="$2"
CHAPTER_LIMIT="$3"
AUTHOR="$4"
OUTPUT_DIR="$5"
TITLE="${6:-${COMIC_PATH_WORD}_${CHAPTER_LIMIT}_chapters}"

DOWNLOADER="$ROOT_DIR/apps/copymanga-headless-lite/copymanga_downloader.py"
PACKAGER="$ROOT_DIR/skills/manga-epub-packager-lite/scripts/manga_packager.py"
PLAN_BUILDER="$ROOT_DIR/skills/manga-epub-packager-lite/scripts/make_merge_plan.py"
MERGER="$ROOT_DIR/skills/manga-epub-packager-lite/scripts/merge_epub_by_order.py"
KCC_CMD="${KCC_CMD:-/tmp/kcc-venv/bin/kcc-c2e}"

DOWNLOAD_ROOT="$OUTPUT_DIR/downloads"
EPUB_ROOT="$OUTPUT_DIR/epubs"
MERGED_ROOT="$OUTPUT_DIR/merged"
MERGED_EPUB="$MERGED_ROOT/${TITLE// /_}.epub"
PLAN_PATH="$EPUB_ROOT/merge-plan.json"

mkdir -p "$OUTPUT_DIR"

python3 "$DOWNLOADER" download-group \
  "$COMIC_PATH_WORD" \
  --group "$GROUP_PATH_WORD" \
  --limit "$CHAPTER_LIMIT" \
  --output-root "$DOWNLOAD_ROOT"

COMIC_JSON="$(python3 "$DOWNLOADER" comic "$COMIC_PATH_WORD" --json)"
COMIC_NAME="$(printf '%s' "$COMIC_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["name"])')"
GROUP_NAME="$(printf '%s' "$COMIC_JSON" | python3 -c 'import json,sys; data=json.load(sys.stdin); groups={g["path_word"]:g["name"] for g in data["groups"]}; print(groups["'"$GROUP_PATH_WORD"'"])')"

python3 "$PACKAGER" \
  --input-root "$DOWNLOAD_ROOT/$COMIC_NAME/$GROUP_NAME" \
  --output-root "$EPUB_ROOT" \
  --kcc-cmd "$KCC_CMD" \
  --profile KS

python3 "$PLAN_BUILDER" \
  --epub-dir "$EPUB_ROOT" \
  --output "$MERGED_EPUB" \
  --title "$TITLE" \
  --author "$AUTHOR" \
  --language zh \
  --description "Generated by run_wsl_copymanga_to_epub.sh" \
  --contributor Piclaw_e2e \
  --plan "$PLAN_PATH"

python3 "$MERGER" --plan "$PLAN_PATH"

printf 'DOWNLOAD_ROOT=%s\n' "$DOWNLOAD_ROOT"
printf 'EPUB_ROOT=%s\n' "$EPUB_ROOT"
printf 'MERGED_EPUB=%s\n' "$MERGED_EPUB"

